### ISSUE TITLE
sm64pc does not save savegame

### ISSUE THREAD

**Issue by superbonaci** [machinebox/appify#11]
I've compiled [sm64pc](https://github.com/sm64pc/sm64pc) with this command:
````
gmake OSX_BUILD=1
````

Then made the app bundle:
````
cd ~
~/go/bin/appify -name "SuperMario64" -icon ~/Downloads/mario64.png ~/sm64pc/build/us_pc/sm64.us.f3dex2e 
````

The problem is, savegame is stored in file `sm64_save_file.bin` next to executable. Also `sm64config.txt` is created for input key mapping. But for some reason writing to folder `~/SuperMario64.app/Contents/MacOS/` is not possible. How could I fix this?

Also, don't know how to debug or view the terminal messages which would be shown if I just run the command `sm64.us.f3dex2e` directly.

**Comment by Zoltar007** [comment]
This is only an issue with the Master branch. In the Nightly branch, the savegame & config file location were changed to `~\Application Support\sm64pc`. If you're still using the Master branch, you can get around the issue with the savegame & config files failing to create inside the app bundle by creating a shell script with the following contents, then point the `CFBundleExecutable` key in the `Info.plist` file at it instead of the binary:
```
#!/bin/bash
cd "${0%/*}"
./sm64.us.f3dex2e
```

Edit: As this has nothing to do with Appify, this issue should probably be closed.

**Comment by superbonaci** [comment]
Fixed on sm64pc repo.
